title: <p slign="center" > Gaurav Parmar </p>
logo: /assets/img/Gaurav.jpg
description:
  <p align="center">
  <a href = "pdf/resume.pdf"> Resume </a>
  <a href = "https://www.linkedin.com/in/gaurav-parmar-b306302b/l> LinkedIn </a>
  <a href = "https://github.com/gaurav619/>GitHub </a>
  
  
  <br>
  I'm working on Big Data, Spark, python on project related to insurance domain.
  Where we deal with problems like customer data analysis, fraud detection, understand market growth and act accordingly
  <br>
  </p>
